pipeline {
    agent none
    stages {
        stage('Build'){
            agent {
                docker {
                    image 'maven:3.6.2-jdk-11'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            environment {
                STUDENTDATA_SECRET = credentials('STUDENTDATA_SECRET')
            }
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
    }
}