pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
        }
    }

    stages {
        stage('maven'){
            steps {
                sh 'mvn --version'
            }
        }
    }
}